<?xml version="1.0"?>
<robot name="alice" xmlns:xacro="http://ros.org/wiki/xacro">


<xacro:property name="M_PI" value="3.1415926535897931"/>
<xacro:property name="DEG2RAD" value="0.017453292" />

<gazebo> 
	<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"> 
		<robotNamespace>/alice</robotNamespace> 
	</plugin> 
</gazebo>

<!-- Dynamixel stand-->

<xacro:macro name="make_box" params="name x y z mass length width height" >
  <link name="${name}" >
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertial>
          <mass value="${mass}"/>
          <origin xyz="${x} ${y} ${z}"/>
          <inertia ixx="${0.0833333 * mass * (height**2 + length**2)}" ixy="0.0" ixz="0.0"
          iyy="${0.0833333 * mass * (width**2 + length**2)}" iyz="0.0"
          izz="${0.0833333 * mass * (width**2 + height**2)}" />
      </inertial>
    <visual name="visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <box size="${length} ${width} ${height}" />
        </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length + 0.09} ${width + 0.09}  ${height + 0.09}" />
        </geometry>
    </collision>
  </link>
</xacro:macro>

<xacro:make_box name="head_stand_link" mass="0.1" length="0.05" width="0.03" height="0.03" x="0" y="0" z="0" />
<xacro:make_box name="front_xtion_link" mass="0.01" length="0.035" width="0.18" height="0.025" x="0" y="-0.08" z="-0.06" />

<link name="head_pitch_link">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertial>
        <origin xyz="0.0 0 0" />
        <mass value="1" />
        <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
      </inertial>
      <visual name="visual">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="0.01 0.01 0.01" />
            <!--mesh filename="package://alice_description/models/box.dae" scale="0.05 0.03 0.03" /-->
          </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="0.01 0.01 0.01" />
            <!--mesh filename="package://alice_description/models/box.dae" scale="0.09 0.09 0.07" /-->
          </geometry>
      </collision>
    </link>

<joint name="head_stand_joint" type="fixed"> <!-- Connection between chassis and bottom rectangular box -->
	<origin rpy="0 0.0 0" xyz=" 0.25 0.0 0.025"/>
	<parent link="top_bar"/>
	<child link="head_stand_link"/>	
</joint>


<!-- First Left to Right Dynamixel -->
    <joint name="head_yaw_joint" type="revolute">
	    <origin rpy="0 0 0" xyz=" 0.015 0 0.03"/>
	    <parent link="head_stand_link"/>
	    <child link="head_yaw_link"/>
	    <axis xyz="0 0 1"/>
	    <limit lower="${-M_PI/2}" upper="${M_PI/2}" effort="10" velocity="${50*DEG2RAD}" />
            <dynamics damping="0.7"/>
    </joint>

    <transmission name="head_yaw_joint_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="head_yaw_joint_motor" >
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
        <joint name="head_yaw_joint" >
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	</joint>
        <mechanicalReduction>1</mechanicalReduction>
        <motorTorqueConstant>1</motorTorqueConstant>
        <pulsesPerRevolution>10000</pulsesPerRevolution>
    </transmission>

    <link name="head_yaw_link">
	    <origin rpy="0 0 0" xyz="0 0 0"/>
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="0.1" />
            <inertia ixx="${0.0833333 * 1 * (0.03**2+ 0.03**2)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * 1 * (0.05**2 + 0.03**2)}" iyz="0.0"
        izz="${0.0833333 * 1 * (0.03**2 + 0.05**2)}" />
        </inertial>
	    <visual name="visual">
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		    <geometry>
		      <box size="0.05 0.03 0.03" />
        		<!--mesh filename="package://alice_description/models/box.dae" scale="0.05 0.03 0.03" /-->
      		</geometry>
	    </visual>
	    <collision>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
      		<geometry>
      		   <box size="0.09 0.09 0.09" />
        		<!--mesh filename="package://alice_description/models/box.dae" scale="0.09 0.07 0.07" /-->
      		</geometry>
	    </collision>
    </link>


<!-- Second Up to Down Dynamixel -->
    <joint name="head_pitch_joint" type="revolute">
	    <origin rpy="${M_PI/2} 0.0 0.0" xyz=" 0.015 0 0.0"/> <!-- rpy="${M_PI/2} -0.04 0.0"-->
        <parent link="head_yaw_link"/>
	    <child link="head_pitch_link"/>
	    <axis xyz="0 0 1"/>
	    <limit lower="${0}" upper="${M_PI}" effort="10" velocity="${50*DEG2RAD}"/>
        <dynamics damping="0.7"/>
    </joint>

    <transmission name="head_pitch_joint_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="head_pitch_joint_motor" >
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
        <joint    name="head_pitch_joint" >
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	</joint>
        <mechanicalReduction>50</mechanicalReduction>
        <motorTorqueConstant>1</motorTorqueConstant>
        <pulsesPerRevolution>10000</pulsesPerRevolution>
    </transmission>


<!-- Front Xtion -->



<!-- Gazebo color plugin for xtion -->
<gazebo reference="front_xtion_link">
	<selfCollide>false</selfCollide>
	<static>true</static>
	<turnGravityOff>false</turnGravityOff>
	<sensor type="depth" name="front_xtion">
		<pose>0 0 0 0 0 0</pose>
		<always_on>1</always_on>
		<visualize>true</visualize>
		<camera>
			<horizontal_fov>1.047</horizontal_fov>
			<image>
				<width>640</width>
				<height>480</height>
				<format>R8G8B8</format>
			</image>
			<depth_camera></depth_camera>
			<clip>
				<near>0.1</near>
				<far>100</far>
			</clip>
		</camera>
		<plugin name="camera_controller" filename="libgazebo_ros_openni_kinect.so">
			<alwaysOn>true</alwaysOn>
			<updateRate>30.0</updateRate>
			<cameraName>front_xtion</cameraName>
			<frameName>front_rgb_optical_link</frameName>
			<imageTopicName>rgb/image_raw</imageTopicName>
			<depthImageTopicName>depth/image_raw</depthImageTopicName>
			<pointCloudTopicName>depth/points</pointCloudTopicName>
			<cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
			<depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
			<pointCloudCutoff>0.0</pointCloudCutoff>
			<pointCloudCutoffMax>4.5</pointCloudCutoffMax>
			<hackBaseline>0.07</hackBaseline>
			<distortionK1>0.0</distortionK1>
			<distortionK2>0.0</distortionK2>
			<distortionK3>0.0</distortionK3>
			<distortionT1>0.0</distortionT1>
			<distortionT2>0.0</distortionT2>
			<CxPrime>0.0</CxPrime>
			<Cx>0.0</Cx>
			<Cy>0.0</Cy>
			<focalLength>0.0</focalLength>
		</plugin>
	</sensor>
</gazebo>


<joint name="head_pitch_to_front_xtion" type="fixed"> <!-- Connection between top bar and front -->
	<origin rpy=" ${-M_PI/2} 0 ${-M_PI/2 + 0.04}" xyz="0.055 0 -0.06"/> <!-- <origin rpy=" ${-M_PI/2 + 0.06} -0.04 ${-M_PI/2 - 0.05}" xyz="0.06 -0.02 -0.07"/> -->
	<child link="front_xtion_link"/>
	<parent link="head_pitch_link"/>
</joint>

<link name="front_rgb_optical_link"/>

<joint name="front_xtion_to_rgb_optical" type="fixed"> <!-- Connection between top bar and front -->
	<origin rpy="${-M_PI/2} 0 ${-M_PI/2}" xyz="0.00 -0.0 0.00"/>
	<parent link="front_xtion_link"/>
	<child link="front_rgb_optical_link"/>
</joint>



</robot>
