scan_filter_chain:
- name: angleleft
  type: LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 1.53589
    upper_angle: 1.75806
- name: angleright
  type: LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -1.75806
    upper_angle: -1.53589
- name: anglerightfar
  type: LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -2.4
    upper_angle: -2.1
- name: box
  type: LaserScanBoxFilter
  params:
    box_frame: laser
    min_x: -1.0
    max_x: 0.02
    min_y: -0.25
    max_y: 0.25
    min_z: -1.0
    max_z: 1.0
