m1n6s200:
  effort_finger_trajectory_controller:
    gains:
      m1n6s200_joint_finger_1: {p: 10.2, d: 0, i: 0, i_clamp: 1}
      m1n6s200_joint_finger_2: {p: 10.2, d: 0, i: 0, i_clamp: 1}
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.5
      m1n6s200_joint_finger_1: {trajectory: 0.75, goal: 0.9}
      m1n6s200_joint_finger_2: {trajectory: 0.75, goal: 0.9}
    joints:
      - m1n6s200_joint_finger_1
      - m1n6s200_joint_finger_2
    type: effort_controllers/JointTrajectoryController
    stop_trajectory_duration: 0.5
    state_publish_rate:  125
    action_monitor_rate: 10
  velocity_joint_trajectory_controller:
    gains:
      m1n6s200_joint_1: {p: 10.2, d: 0.1, i: 0, i_clamp: 1}
      m1n6s200_joint_2: {p: 10.2, d: 0.1, i: 0, i_clamp: 1}
      m1n6s200_joint_3: {p: 10.2, d: 0.1, i: 0, i_clamp: 1}
      m1n6s200_joint_4: {p: 10.2, d: 0.1, i: 0, i_clamp: 1}
      m1n6s200_joint_5: {p: 10.2, d: 0.1, i: 0, i_clamp: 1}
      m1n6s200_joint_6: {p: 10.2, d: 0.1, i: 0, i_clamp: 1}
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.5
      m1n6s200_joint_1: {trajectory: 0.75, goal: 0.5}
      m1n6s200_joint_2: {trajectory: 0.75, goal: 0.5}
      m1n6s200_joint_3: {trajectory: 0.75, goal: 0.5}
      m1n6s200_joint_4: {trajectory: 0.75, goal: 0.5}
      m1n6s200_joint_5: {trajectory: 0.75, goal: 0.5}
      m1n6s200_joint_6: {trajectory: 0.75, goal: 0.5}
    joints:
      - m1n6s200_joint_1
      - m1n6s200_joint_2
      - m1n6s200_joint_3
      - m1n6s200_joint_4
      - m1n6s200_joint_5
      - m1n6s200_joint_6
    type: velocity_controllers/JointTrajectoryController
    stop_trajectory_duration: 0.5
    state_publish_rate:  125
    action_monitor_rate: 10
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
   
  
    